version: '3'
services:
  postgres:
    build:
      context: 🐳where can I find the docker file?🐳
      dockerfile: 🐳What is the name of the docker file?🐳
    ports:
      - 5432:🐳what port should requests go to inside the container?🐳
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
  backend:
    build:
      context: 🐳where can I find the docker file?🐳
      dockerfile:  🐳What is the name of the docker file?🐳
    ports:
      - 🐳what port on your computer do you want to take requests on?🐳:3001
    volumes:
      - ./backend:/app/
      - /app/node_modules
    links:
      - postgres
    depends_on: 
      - postgres
    environment:
      PGUSER: postgres
      PGHOST: postgres
      PGDATABASE: postgres
      # 🐳Define an environment variable called "PGPASSWORD" that has an value of "password" (remove all quotations after you finish)🐳
      PGPORT: 5432

  # 🐳
  # Create a service called "frontend" that is responsible for configs:
  # building and starting container running the react app.

  # Hints:
  #   1. look inside the frontend directory!
  #   2. you can start a react app with the command: npm start
  #   3. we want requests on OUR port 3000 to go get mapped INTO the
  #     CONTAINER's port 3000 .
  #   4. Make sure your indentation matches the indentation of the other services!
  #   5. You will need two volumes: ./frontend:/app/ and /app/node_modules

  # 🐳